added documentation about the FHIR Package source
FirelyTeam/firely-docs-firely-net-sdk pull request #18
Opened 2022-06-13 14:07 UTC by mmsmits

2022-06-23 11:50 UTC, ewoutkramer requested changes

2022-06-23 11:50 UTC, ewoutkramer commented on fhir-package-source/package-source.rst
> +As of SDK version 4.0 you can use a FHIR Package source to resolve FHIR artifacts like ``StructureDefinitions``, ``ValueSets``, and ``CodeSystems`` from one ore multiple FHIR Package.
"one or more FHIR Package" -> "one or more FHIR NPM  packages"   

I think the term "package" is quite overloaded, so using the qualifier NPM at least once will help to disambiguate.

2022-06-23 11:50 UTC, ewoutkramer commented on fhir-package-source/package-source.rst
> +This can be from the FHIR core packages, but it can be from any FHIR Package you like. These for FHIR artifacts are needed for example for validating resources. Or to generate snapshots of profiles.
"These _for_ FHIR"?

2022-06-23 11:50 UTC, ewoutkramer commented on fhir-package-source/package-source.rst
> +There are multiple ways to create a ``FhirPackageSource`` instance, that include the packages you want to use.
"...that include the packages" = "to include the packages" ?

2022-06-23 11:50 UTC, ewoutkramer commented on fhir-package-source/package-source.rst
> +.. note:: You may need an active internet connection to use this. This function will first check if the specified packages are already installed locally before searching for the packages online.
Maybe we should talk about the location where the packages are cached in this case?

2022-06-23 11:50 UTC, ewoutkramer commented on fhir-package-source/package-source.rst
> +The most common use case for the FHIR Package source is to resolve conformance resources like ``StructureDefinitions``, ``ValueSets``, and ``CodeSystems``  from specific FHIR packages.
I'd add that it implements `IResourceResolver`

2022-06-23 11:50 UTC, ewoutkramer commented on fhir-package-source/package-source.rst
> +You can also find any resource by their type and id, or any file by their name or relative filepath.
And here, you are talking about `IArtifactResolver`, maybe good to add.

2022-06-23 11:50 UTC, ewoutkramer commented on fhir-package-source/package-source.rst
> +There is also a ``class`` in the SDK called ``CommonFhirPackageSource``. This ``class`` is located in the FHIR version agnostic part of the SDK, and this is actually where all the magic happens.
You don't have to `class` the word class, I have not done so in the rest of the documentation.

2022-06-23 11:50 UTC, ewoutkramer commented on fhir-package-source/package-source.rst
> +
As a reader I am wondering: why do you mention this?  If this is a problem, how do I solve this?  Does CommonFhirPackageSource vs FhirPackageSource have anything to do with that?  If so, what?  Maybe just add an example to show how `new FhirPackageSource()` is equivalent to `new CommonFhirPackageSource(typeof(Patient).Assembly) or something like that.   And explain why you mention the fact that you cannot combine.

2022-07-08 14:56 UTC, vadi2 reviewed
Just a few editorial improvements

2022-07-08 14:56 UTC, vadi2 commented on fhir-package-source/package-source.rst
> +.. note:: You may need an active internet connection to use this. This function will first check if the specified packages are already installed locally before searching for the packages online. FHIR
```suggestion
.. note:: You may need an active internet connection to use this. This function will first check if the specified packages are already installed locally before searching for the packages online. FHIR NPM packages are installed by default in ``C:\Users\{user}\.fhir\packages\`` (Windows), ``/Users/{user}/.fhir/packages/`` (macOS), or ``~/.fhir/packages/`` (Linux).
```

2022-07-08 14:56 UTC, vadi2 commented on fhir-package-source/package-source.rst
> +We see that a ``CommonFhirPackageSource`` including the ModelInspector of the currect FHIR version is created in the constructor, and that all functions in ``FhirPackageSource`` actually just call it
```suggestion
We see that a ``CommonFhirPackageSource``, including the ModelInspector of the currect FHIR version is created in the constructor, and that all functions in ``FhirPackageSource`` actually just call their ``CommonFhirPackageSource`` equivalent right away.
```

2022-07-08 16:03 UTC, mmsmits commented
> Just a few editorial improvements

Thanks @vadi2

2022-07-13 13:07 UTC, ewoutkramer approved these changes

2022-07-13 13:07 UTC, merged