Document the high-level Validation API
FirelyTeam/firely-docs-firely-net-sdk pull request #56
Opened 2023-11-29 08:21 UTC by ewoutkramer

Details how to construct a `Validator`, how to configure it, how to execute a validation and how to interpret the results.

2023-12-11 17:44 UTC, vadi2 approved these changes

2023-12-19 19:25 UTC, virajkanwade commented
https://www.nuget.org/packages/Hl7.Fhir.Validation.Legacy.R4 says ```In the latest release of the [Firely .NET SDK](https://github.com/FirelyTeam/firely-net-sdk) (version 5.0), we have removed the FHIR profile validator (Hl7.Fhir.Validation.Validator). While we are working on a new and faster validator, we have kept the old validator in the SDK for backwards compatibility.```

So is this documentation still valid?

2024-01-04 11:18 UTC, marcovisserFurore requested changes
This documentation does not reflect the latest version of Firely.Fhir.Validation (API)

2024-01-10 08:55 UTC, mmsmits approved these changes

2024-01-10 08:56 UTC, merged