Added documentation for the serializer.
FirelyTeam/firely-docs-firely-net-sdk pull request #8
Opened 2021-07-22 13:09 UTC by ewoutkramer

2021-07-22 14:50 UTC, marcovisserFurore requested changes

2021-07-22 14:50 UTC, marcovisserFurore commented on parsing/system-text-json-serialization.rst
> +This is great for round-tripping, and keeping validation duties out of the serializer avoids duplicate work and helps performance, but it also means one
```suggestion
This is great for round-tripping, and keeping validation duties out of the serializer, avoids duplicate work and helps performance, but it also means one
```

2021-07-29 13:54 UTC, ewoutkramer commented on parsing/system-text-json-serialization.rst
> +This is great for round-tripping, and keeping validation duties out of the serializer avoids duplicate work and helps performance, but it also means one
I'll rewrite it.

2022-02-07 09:36 UTC, marcovisserFurore approved these changes

2022-02-07 11:51 UTC, merged